// This file is auto-generated by the system. Do not edit manually.
export const standardsList = ${JSON.stringify(standards, null, 2)};

export const ENGINEERING_STANDARDS = standardsList.map(s => s.content).join('\\n\\n');

// Backwards compatibility exports
export const STRESS_CONVENTION = "";
export const SUBGRADE_REACTION_CONVENTION = "";
export const GRAPH_AND_TABLE_CONVENTION = "";
export const SITUATIONAL_FEASIBILITY_CONVENTION = "";
export const SEEPAGE_PRESSURE_CONVENTION = "";
export const USER_CONVENTIONS = "";
