// This file is auto-generated by the system. Do not edit manually.
export let generationStandardsList = [
  {
    "id": "def_gen_1",
    "title": "공식 및 수치 범위 노출 절대 금지",
    "content": "🚨 [공식 및 공식 수치 범위 노출 절대 금지 규칙 - 극도로 중요!]: 문제 질문(question) 본문 내에 문제를 해결하는 데 필요한 공학 수식 자체(예: $E_u = 300 s_u$ 등)나 수식의 특정 수치 범위(예: $E_u = (200 \\sim 500)s_u$ 등), 비례 관계 식 등을 **절대로 직접 텍스트로 적어 제공하지 마십시오.** 대신 공식의 명칭(\"비배수 탄성계수 경험식\")이나 변수들의 명칭(\"비배수 전단강도 $s_u$\")만을 제시하고, 학생이 스스로 공식과 범위를 떠올려서 해결하도록 하십시오. (단, 해설(explanation)에서는 학생의 학습을 위해 공식을 상세히 명시하고 계산 과정을 설명해야 합니다.)"
  },
  {
    "id": "def_gen_2",
    "title": "유사/중복 질문 출제 금지",
    "content": "🚨 [유사/중복 질문 출제 절대 금지 - 매우 중요!]: 하나의 공식이나 거동 특성에서 파생되는 변수만 바꾼 형태의 유사한 비례/반비례 질문은 **절대로 중복하여 출제하지 마십시오.** (예: 공식 $A = B \\times C$에 대해 \"B가 증가할 때 A의 변화\"를 묻는 문제를 출제했다면, 동일한 테스트 세트 내에 \"C가 증가할 때 A의 변화\"를 묻는 질문은 사실상 동일한 비례 관계 메커니즘을 묻는 중복 문제이므로 **절대로 같이 내지 말고**, 완전히 다른 공학적 개념이나 새로운 지식을 묻는 독립적인 문제로만 구성하십시오.)"
  },
  {
    "id": "def_gen_3",
    "title": "객관식 정밀성 및 정답 일치 조건",
    "content": "🚨 [객관식 정밀성 및 정답 일치 조건 - 극도로 중요!]: 모든 객관식(4지선다형) 계산 문제나 수치/공학적 판단 문제를 출제할 때, 계산으로 도출된 정확한 정답 수치나 조건이 4개의 보기(options) 중 반드시 정확히 1개로 존재해야 합니다. 절대로 실제 계산 결과와 보기의 수치가 불일치하여, 해설에서 '실제 계산값은 XX이나 보기 중 가장 가까운 YY를 선택합니다'와 같은 어처구니없는 변명을 적는 출제 오류를 범하지 마십시오. 문제를 생성하기 전에 실제 수식을 대입하여 정답을 한 번 더 직접 엄밀하게 계산하고 검증한 후, 그 결과값(토씨 하나 틀리지 않는 정확한 정답)을 보기와 'answer' 필드에 완벽히 일치하도록 기재하십시오."
  }
];

export let GENERATION_STANDARDS = assembleGenerationStandardsPrompt(generationStandardsList);

export function assembleGenerationStandardsPrompt(list) {
  if (!Array.isArray(list) || list.length === 0) {
    return "- 등록된 문제생성 지침 기준이 없습니다.";
  }
  return list
    .map((std, idx) => {
      return `${idx + 1}. **${std.title}**:\n   - ${std.content}`;
    })
    .join("\n");
}

export function updateLiveGenerationStandards(newList) {
  if (Array.isArray(newList)) {
    generationStandardsList = newList;
    GENERATION_STANDARDS = assembleGenerationStandardsPrompt(newList);
    console.log("[GenerationStandards] Live generation standards prompt updated. Count:", newList.length);
  }
}
