// This file is auto-generated by the system. Do not edit manually.
export let lockscreenStandardsList = [
  {
    "id": "source_report_review_first",
    "title": "1단계: 출처 사전 학습 및 출처 기반 질문/답변 연계 문제 출제 철칙",
    "content": "🚨 [1단계: 출처 사전 학습 및 출처 기반 질문/답변 연계 문제 출제 철칙 - 극도로 중요!]: AI는 락스크린 퀴즈 문제를 출제할 때, 가장 첫번째 단계에서 반드시 관련 출처 보고서 및 국가기준/학술문헌(KDS/KCS, 원보고서 본문, Wikipedia Soil Mechanics)의 원문 내용과 핵심 지침을 직접 사전에 학습해야 합니다. 하드코딩되거나 무관한 찌꺼기 더미 문구(K0, Kirsch, Terzaghi 등)를 절대 사용하지 말고, 해당 토픽의 실제 공학 현상 및 정론 지침에 근거하여 문제를 출제하십시오.",
    "updatedAt": new Date().toISOString()
  },
  {
    "id": "def_ls_1",
    "title": "공식, 기준, 숫자 중심 출제",
    "content": "1.락스크린 문제는 반드시 공식(수식 매칭, 변수 정의, 비례 관계 등), 설계 및 시공 기준(KDS 등), 그리고 구체적인 수치/숫자값(상한/하한값, 단위, 상수 등)만 질문 대상으로 삼으십시오. 단순 서술형 개념 설명이나 일반적인 이론 설명에 대한 질문은 절대 출제하지 마십시오.\n2.문제 제출범위 제한 금지\nAI는 문제를 출제할 때 제공된 토픽 문서 텍스트에 포함된 단어들을 단순히 빈칸으로 만들거나 그대로 베끼는 1차원적인 문제 출제를 엄격히 금지합니다. 해당 토픽에 대해 튜터와 대화할 때 도출되는 수준의\n① 거동 원리 및 메커니즘\n② 공식 유도 과정 및 가정 조건\n종합적으로 감안하여 학술적 깊이가 있는 기술사형 응용 문제를 위의 1번 기준으로 출제",
    "updatedAt": "2026-06-28T03:50:02.745Z"
  },
  {
    "id": "def_ls_2",
    "title": "정답 유형 제한",
    "content": "질문은 무조건 \"맞는 것(올바른 것)\" 또는 \"올바른 기준수치/값\"만 고르도록 요구해야 합니다. 절대로 \"틀린 것\", \"올바르지 않은 것\", \"잘못된 것\"을 고르는 문제는 출제하지 마십시오.",
    "updatedAt": "2026-06-28T03:50:02.745Z"
  },
  {
    "id": "user_lockscreen_eooum7e",
    "title": "공식의 각 항목이 가지는 의미를 묻기",
    "content": "이런식의 문제도 좋아 : 공식의 각 항목이 가지는 의미\n예시)\n- 변수위 투수계수 공식\n$$k = 2.303 \\dfrac{aL}{At} \\log_{10} \\left( \\dfrac{h_1}{h_2} \\right)$$\n\n분자 dfrac{aL}{At}가 가지는 직관적의미는?",
    "updatedAt": "2026-06-28T03:50:02.745Z"
  },
  {
    "id": "user_lockscreen_interval_10min",
    "title": "웹 시스템 사용 종료 후 10분 경과 시 락스크린 제공 지침",
    "content": "락스크린 주기는 웹 시스템 사용 종료 후 10분이 경과되었을 때 제공하며, 10분 이내로 재접속 시에는 등장하지 않습니다.",
    "updatedAt": new Date().toISOString()
  },
];

export let LOCKSCREEN_STANDARDS = assembleLockscreenStandardsPrompt(lockscreenStandardsList);

export function assembleLockscreenStandardsPrompt(list) {
  if (!Array.isArray(list) || list.length === 0) {
    return "- 등록된 락스크린 출제 지침 기준이 없습니다.";
  }
  return list.map((std, idx) => `${idx + 1}. **${std.title}**:\n   - ${std.content}`).join('\n');
}

export function updateLiveLockscreenStandards(newList) {
  lockscreenStandardsList = newList;
  LOCKSCREEN_STANDARDS = assembleLockscreenStandardsPrompt(newList);
}
