// This file is auto-generated by the system. Do not edit manually.
export let lockscreenStandardsList = [
  {
    "id": "def_ls_1",
    "title": "공식, 기준, 숫자 중심 출제",
    "content": "락스크린 문제는 반드시 공식(수식 매칭, 변수 정의, 비례 관계 등), 설계 및 시공 기준(KDS 등), 그리고 구체적인 수치/숫자값(상한/하한값, 단위, 상수 등)만 질문 대상으로 삼으십시오. 단순 서술형 개념 설명이나 일반적인 이론 설명에 대한 질문은 절대 출제하지 마십시오."
  }
];

export let LOCKSCREEN_STANDARDS = assembleLockscreenStandardsPrompt(lockscreenStandardsList);

export function assembleLockscreenStandardsPrompt(list) {
  if (!Array.isArray(list) || list.length === 0) {
    return "- 등록된 락스크린 출제 지침 기준이 없습니다.";
  }
  return list.map((std, idx) => `${idx + 1}. **${std.title}**:\n   - ${std.content}`).join('\n');
}

export function updateLiveLockscreenStandards(newList) {
  lockscreenStandardsList = newList;
  LOCKSCREEN_STANDARDS = assembleLockscreenStandardsPrompt(newList);
}
