// This file is auto-generated by the system. Do not edit manually.
export let lockscreenStandardsList = [
  {
    "id": "def_ls_1",
    "title": "공식, 기준, 숫자 중심 출제",
    "content": "1.락스크린 문제는 반드시 공식(수식 매칭, 변수 정의, 비례 관계 등), 설계 및 시공 기준(KDS 등), 그리고 구체적인 수치/숫자값(상한/하한값, 단위, 상수 등)만 질문 대상으로 삼으십시오. 단순 서술형 개념 설명이나 일반적인 이론 설명에 대한 질문은 절대 출제하지 마십시오.\n2.문제 제출범위 제한 금지\nAI는 문제를 출제할 때 제공된 토픽 문서 텍스트에 포함된 단어들을 단순히 빈칸으로 만들거나 그대로 베끼는 1차원적인 문제 출제를 엄격히 금지합니다. 해당 토픽에 대해 튜터와 대화할 때 도출되는 수준의\n① 거동 원리 및 메커니즘\n② 공식 유도 과정 및 가정 조건\n종합적으로 감안하여 학술적 깊이가 있는 기술사형 응용 문제를 위의 1번 기준으로 출제"
  },
  {
    "id": "user_lockscreen_61d70z3",
    "title": "공식",
    "content": "1.공식의 주요한 상수/변수를 가리고 그것을 묻는 문제도 좋습니다.\n2.공식의 특정한 항을 가리키고 그 항이 가지는 내재적 의미를 묻는것도 좋습니다."
  },
  {
    "id": "def_ls_2",
    "title": "정답 유형 제한",
    "content": "질문은 무조건 \"맞는 것(올바른 것)\" 또는 \"올바른 기준수치/값\"만 고르도록 요구해야 합니다. 절대로 \"틀린 것\", \"올바르지 않은 것\", \"잘못된 것\"을 고르는 문제는 출제하지 마십시오."
  },
  {
    "id": "def_ls_3_blind_intuition",
    "title": "수식 조각 블라인드 채우기 및 직관적 의미 출제 필수화",
    "content": "🚨 [수식 조각 블라인드 채우기 및 직관적 의미 질문 필수화 - 극도로 중요!]:\n단순히 공식 전체를 보여주고 단순 비례/반비례 관계를 묻는 너무 쉬운 1차원적 문항 출제를 지양하십시오. 대신 아래 두 가지 유형으로 출제 수준을 대폭 상향하십시오:\n1. 수식 조각 블라인드(빈칸) 처리: 공식을 제시하고 수식의 특정 파트(예: 변수수위 투수 공식의 aL, A(t2-t1) 파트, 혹은 ln(h1/h2) 파트 등)를 블라인드(빈칸) 처리하여 그 자리에 들어갈 알맞은 수식 조각이나 변수를 고르는 문제를 구성하십시오.\n2. 수식 조각의 직관적/물리적 의미 질문: 공식의 각 파트(예: 변수수위 투수공식에서 분자의 aL이 스탠드파이프 및 공시체 길이를 나타낸다는 점, ln(h1/h2) 수두비가 의미하는 물리적 감쇠/투수 메커니즘 등)가 담고 있는 수리학적/공학적 직관적 의미를 묻는 응용문제를 출제하십시오."
  }
];

export let LOCKSCREEN_STANDARDS = assembleLockscreenStandardsPrompt(lockscreenStandardsList);

export function assembleLockscreenStandardsPrompt(list) {
  if (!Array.isArray(list) || list.length === 0) {
    return "- 등록된 락스크린 출제 지침 기준이 없습니다.";
  }
  return list.map((std, idx) => `${idx + 1}. **${std.title}**:\n   - ${std.content}`).join('\n');
}

export function updateLiveLockscreenStandards(newList) {
  lockscreenStandardsList = newList;
  LOCKSCREEN_STANDARDS = assembleLockscreenStandardsPrompt(newList);
}
