// This file is auto-generated by the system. Do not edit manually.
export let otherStandardsList = [
  {
    "id": "user_other_default_1",
    "title": "기타 종합 프롬프트 및 지침 관리",
    "content": "AI 튜터 및 채점관은 기타 요구사항 및 특수 지침이 있을 경우 본 기타 지침 항목에 기재된 모든 내용들을 최우선적으로 존중하여 반영하십시오.",
    "updatedAt": "2026-07-25T00:00:00.000Z"
  }
];

export function assembleOtherStandardsPrompt(list) {
  if (!Array.isArray(list) || list.length === 0) {
    return "- 등록된 기타 지침 기준이 없습니다.";
  }
  return list.map((std, idx) => `${idx + 1}. **${std.title}**:\n   - ${std.content}`).join('\n');
}

export let OTHER_STANDARDS = assembleOtherStandardsPrompt(otherStandardsList);

export function updateLiveOtherStandards(newList) {
  otherStandardsList = newList;
  OTHER_STANDARDS = assembleOtherStandardsPrompt(newList);
}
