// This file is auto-generated by the system. Do not edit manually.
export let otherStandardsList = [
  {
    "id": "user_other_default_1",
    "title": "기타 종합 프롬프트 및 시스템 절대 수칙",
    "content": "AI 튜터 및 채점관은 기타 요구사항 및 특수 지침이 있을 경우 본 기타 지침 항목에 기재된 모든 내용들을 최우선적으로 존중하여 반영하십시오.",
    "updatedAt": "2026-07-25T00:00:00.000Z"
  },
  {
    "id": "user_other_default_2",
    "title": "복습 엔진 및 믹스 복습 절대 보존 수칙",
    "content": "기존 '복습하기' 및 '믹스복습' 핵심 엔진 코딩은 절대로 직접 수정하거나 변경하지 않으며, 모든 카드 및 표 렌더링 기능은 100% 독립된 개별 플러그인 생태계 내부에서만 격리되어 구동되어야 합니다.",
    "updatedAt": "2026-07-25T00:00:00.000Z"
  },
  {
    "id": "user_other_default_3",
    "title": "KaTeX LaTeX 수학 수식 보존 및 공학 기호 정밀 렌더링 수칙",
    "content": "AI 튜터 및 복습 엔진의 기존 KaTeX LaTeX 수학 수식 렌더링 시스템을 절대 건드리지 않고, 그리스 문자 nu(포아송비 ν), sigma(응력 σ), tau(전단응력 τ) 등 공학 수식 기호가 훼손 없이 정밀하게 표출되도록 유지합니다.",
    "updatedAt": "2026-07-25T00:00:00.000Z"
  },
  {
    "id": "user_other_default_6",
    "title": "사용자 명시적 지시 기반 푸시/배포 엄수 수칙",
    "content": "git push 및 프로덕션 배포는 자동 수행하지 않으며, 오직 사용자가 '푸시해' 또는 '배포해'라고 명시적으로 지시할 때만 실행합니다.",
    "updatedAt": "2026-07-25T00:00:00.000Z"
  }
];

export let OTHER_STANDARDS = assembleOtherStandardsPrompt(otherStandardsList);

export function assembleOtherStandardsPrompt(list) {
  if (!Array.isArray(list) || list.length === 0) {
    return "- 등록된 기타 지침 기준이 없습니다.";
  }
  return list.map((std, idx) => `${idx + 1}. **${std.title}**:\n   - ${std.content}`).join('\n');
}

export function updateLiveOtherStandards(newList) {
  otherStandardsList = newList;
  OTHER_STANDARDS = assembleOtherStandardsPrompt(newList);
}
